/******************************************************************************
** Copyright, 1999 - 2018, Intergraph Corporation. All rights reserved.
**
** CREATED: 2019-02-18
** PURPOSE: Versioning Header - This file is generated by versioner.py
**
******************************************************************************/

#define NCS_ECWJP2_VER_MAJOR 5
#define NCS_ECWJP2_VER_MINOR 4
#define NCS_ECWJP2_VER_SERVICE 0
#define NCS_ECWJP2_VER_BUILD 1596
#define NCS_ECWJP2_VER_MAJOR_STR "5"
#define NCS_ECWJP2_VER_MINOR_STR "4"
#define NCS_ECWJP2_VER_SERVICE_STR "0"
#define NCS_ECWJP2_VER_BUILD_STR "1596"
#define NCS_ECWJP2_VER NCS_ECWJP2_VER_MAJOR
#define NCS_ECWJP2_VERSION_NUMBER 5.4
#define NCS_ECWJP2_VERSION_STRING "5.4"
#define NCS_ECWJP2_FULL_VERSION_NUMBER 5.4.0.1596
#define NCS_ECWJP2_FULL_VERSION_STRING "5,4,0,1596\0"
#define NCS_ECWJP2_FULL_VERSION_STRING_NO_NULL "5,4,0,1596"
#define NCS_ECWJP2_FULL_VERSION_STRING_DOT_DEL "5.4.0.1596"
